### ISSUE TITLE
Question: Color Feed and Diffs

### ISSUE THREAD

**Issue by wrburgess** [erwstout/node-mlb-api#1]
You make mention in your comments that folks should be careful about hitting the Color Feed resource and not using the diff approach. Curious if allowing that parameter in your API is something you want to do. I might hack on it and add a PR.

**Comment by erwstout** [comment]
Yes feel free to make a PR for this. Currently in what I'm building I don't
have a need for the diffs so it's pretty low on my priority list although I
see why it would be useful and smart. Im absolutely open to additions and
enhancements.

**Comment by erwstout** [comment]
Closing this, feel free to submit a PR if you've done it.
